server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lockmate_db
    driver-class-name: org.postgresql.Driver
    username: lm_user
    password: AveryLongLMPassword123!
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or 'none' in production
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    livereload:
      enabled: true   # enables automatic browser reload
  thymeleaf:
    cache: false      # disables caching so template changes reload instantly

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: lockmate-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  bootstrapAddress: kafka:9092
  commandTopic: maglock-commands
